CREATE TABLE IF NOT EXISTS phrases (
    id SERIAL PRIMARY KEY,
    phrase TEXT UNIQUE NOT NULL,
    ai_likelihood FLOAT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS words (
    id SERIAL PRIMARY KEY,
    word TEXT UNIQUE NOT NULL,
    ai_likelihood FLOAT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
